### ISSUE TITLE
IOS8 or above, the application can not stop

### ISSUE THREAD

**Issue by jindejava** [vigossjjj/CrashMonkey4IOS#1]
IOS8 or above, the end of the script, the application has been running sometimes.

**Comment by boxerxing** [comment]
@jindejava ,Thank you for this feedback.I think this issue maybe happened after running monkey long time.There are lot of screenshots and .trace file need to deal with the program after finish all monkey events. We will fix this issue in next version.

**Comment by vigossjjj** [comment]
@jindejava update and try again! I face the issue on UIAutomation test, also. So i don't think it related to CrashMonkey4IOS.
