### ISSUE TITLE
按照说明配置好环境后运行命令报错，日志如下

### ISSUE THREAD

**Issue by Hellengo** [vigossjjj/CrashMonkey4IOS#14]
localhost:CrashMonkey4IOS-master Hellengo$ bin/smart_monkey
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14/rbconfig.rb:213: warning: Insecure world writable dir /bin in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- erubis (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/Hellengo/.Trash/CrashMonkey4IOS-master 下午6.16.21/lib/smart_monkey/monkey_runner.rb:7:in `<module:UIAutoMonkey>'
    from /Users/Hellengo/.Trash/CrashMonkey4IOS-master 下午6.16.21/lib/smart_monkey/monkey_runner.rb:3:in`<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/Hellengo/.Trash/CrashMonkey4IOS-master 下午6.16.21/lib/smart_monkey.rb:3:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from bin/smart_monkey:10:in`<main>'

**Comment by vigossjjj** [comment]
缺少Ruby的erubis模块
