### ISSUE TITLE
在xcode7下执行monkey报错

### ISSUE THREAD

**Issue by Solomo-vip** [vigossjjj/CrashMonkey4IOS#15]
执行命令，设备为iphone4s模拟器
$./smart_monkey -a com.vipshop.lf -w 806DCE99-A1AB-46C1-8D46-AAF4B9820ECE
日志如下：
/Users/jincheng/Documents/IOS Monkey/CrashMonkey4IOS/lib/smart_monkey/monkey_doctor.rb:7: warning: Insecure world writable dir /usr/bin in PATH, mode 040757
INSTRUMENTS_TRACE_PATH : /Users/jincheng/Documents/IOS Monkey/CrashMonkey4IOS/bin/*.trace
RESULT_BASE_PATH : /Users/jincheng/Documents/IOS Monkey/CrashMonkey4IOS/bin/smart_monkey_result
{:app_path=>"com.vipshop.lf", :device=>"806DCE99-A1AB-46C1-8D46-AAF4B9820ECE", :run_count=>1, :time_limit_sec=>nil, :detail_event_count=>50}
xcode-select: error: tool 'instruments' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
Invalid device, Please given a vaild device!
xcode-select: error: tool 'instruments' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by vigossjjj** [comment]
应该是你的目录权限的问题
