### ISSUE TITLE
WARN: no response in log, trigger re-launch action.

### ISSUE THREAD

**Issue by loneyao** [vigossjjj/CrashMonkey4IOS#19]
2015-08-20 09:32:20.931 instruments[564:11839] Attempting to set event horizon when core is not engaged, request ignored
2015-08-20 01:31:26 +0000 Screenshot captured.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log

**Comment by vigossjjj** [comment]
问题描述不清，固关闭！

**Comment by cheng19930302** [comment]
我现在也是这个问题，启动app后进入到首页就不动了，app也没挂，正常的；

**Comment by cheng19930302** [comment]
@vigossjjj 请问怎么处理呢？Attempting iOS device system log capture via deviceconsole.
BundleID was found: com.jk724.health
Run: ["instruments", "-w", "21625055ec5e44fb8061a719ad66682d3b92c441", "-t", "/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Resources/templates/Automation.tracetemplate", "com.jk724.health", "-e", "UIASCRIPT", "/Users/jon/smart_monkey_result/report_20170427134442/custom.js", "-e", "UIARESULTSPATH", "/Users/jon/smart_monkey_result/report_20170427134442"]
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
WARN: no response in log, trigger re-launch action.
