### ISSUE TITLE
环境配置完成后无法运行

### ISSUE THREAD

**Issue by perfmeta** [vigossjjj/CrashMonkey4IOS#2]
按照这个步骤：
1,安装Ruby运行环境，建议不要使用OS X自带版本，可自行使用RVM安装最新版的Ruby。建议使用淘宝镜像安装，速度比较快，$ sed -i -e 's/ftp.ruby-lang.org\/pub\/ruby/ruby.taobao.org\/mirrors\/ruby/g' ~/.rvm/config/db
2,确保gem可用，也建议使用淘宝镜像 gem sources --remove https://rubygems.org/;gem sources -a http://ruby.taobao.org/;gem sources -l
3,安装Homebrew ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

安装完使用命令：

crash_monkey -a com.51fanli.fanli -w 728cd07ef9a84dfeb0c04cc20d02a68d3162cd8e -n 1 500

提示:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- erubis (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/sh428/Desktop/CrashMonkey4IOS-master/lib/crash_monkey/monkey_runner.rb:7:in `<module:UIAutoMonkey>'
    from /Users/sh428/Desktop/CrashMonkey4IOS-master/lib/crash_monkey/monkey_runner.rb:3:in`<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/sh428/Desktop/CrashMonkey4IOS-master/lib/crash_monkey.rb:2:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/sh428/Desktop/CrashMonkey4IOS-master/bin/crash_monkey:8:in`<main>'
SH428deMacBook-Air:CrashMonkey4IOS-master sh428$ 

请问我的步骤还缺少什么？或者哪一步可能出错误，请告知，万分感谢！

**Comment by boxerxing** [comment]
@testly 从CrashMonkey4IOS的README来看你因该是已经安装了ruby和gem，这两个是依赖安装，运行Monkey还需要重要的shell 工具brew install libimobiledevice，使用brew进行安装，不要使用sudo，具体的一些问题可以参看：https://github.com/vigossjjj/CrashMonkey4IOS/blob/master/Troubleshooting.md中的解决方案，希望能帮助到你。

**Comment by perfmeta** [comment]
@boxerxing libimobiledevice已经安装了！  不用sudo 执行，用什么来执行 sh reset.sh呢

**Comment by boxerxing** [comment]
@testly 我个人推荐 手动按照reset.sh中的命令一步一步安装，这样问题出在哪里好分析，安装之前一定保证你的ruby正常，然后更新brew工具模块，确保brew update成功后在安装libimobiledevice就行

**Comment by perfmeta** [comment]
@boxerxing       按reset。sh 一步一步弄下来 没有问题但最后执行命令 提示   ：-bash: crash_monkey: command not found
哎，

**Comment by boxerxing** [comment]
@testly crash_monkey是一个ruby的执行文件， 在其路径下启用该文件的执行权限，chmod a+x crash_monkey ，如果是非命令行的话可以通过双击crash_monkey查看下该文件的输出，试试，不行再联系我

**Comment by boxerxing** [comment]
More troubles please first refer to doc：
https://github.com/vigossjjj/CrashMonkey4IOS/blob/master/Troubleshooting.md
