### ISSUE TITLE
WARN: no response in log, trigger re-launch action.

### ISSUE THREAD

**Issue by RogerGan** [vigossjjj/CrashMonkey4IOS#21]
应用运行过程中，直接花键＋shift＋H，回到主界面，程序出现标题提示，且无法恢复

**Comment by vigossjjj** [comment]
@RogerGan 有日志没？

**Comment by RogerGan** [comment]
@vigossjjj 已经给了必现步骤，模拟器运行的时候，直接花键＋shift＋H，回到主界面，这时候CrashMonkeyIOS就会出现死循环，一直提示标题的提示

**Comment by RogerGan** [comment]
@vigossjjj 我查了一下原因，是command_helper里面的run_process执行失效了，我测试了一下，发现relaunch_app方法是不ok的。
![image](https://cloud.githubusercontent.com/assets/10350086/9754633/c797c8a6-56fd-11e5-9fa5-4461ca2a7d04.png)

**Comment by RogerGan** [comment]
补充一下：idevicedebug -u uuid run bundleid >/dev/null 2>&1 &  命令在iphone6p上执行时ok的，模拟器上不行

**Comment by RogerGan** [comment]
@vigossjjj 我自己简单的测试了一下，我的改造，怎么操作，我把我的代码和进来呢？
![image](https://cloud.githubusercontent.com/assets/10350086/9755502/09a27b72-5705-11e5-9325-449684669590.png)

**Comment by vigossjjj** [comment]
@RogerGan 的确iOS的模拟器Re-Launch处理还没有完善，非常感谢你的提交！
