### ISSUE TITLE
-n 2 -t 50后，事件数变为99999999

### ISSUE THREAD

**Issue by muchild** [vigossjjj/CrashMonkey4IOS#24]
执行smart_monkey -a BundleID -n 2 -d //Users/jane/Documents -t 50 --event-number 60 后，monkey.config.numberOfEvents变为了99999999，这是为啥？

**Comment by muchild** [comment]
刚看了UIAutoMonkey.js，原来是run either by minutesToRun or numberOfEvents. Only one of these can set. (To use minutes you can use config.numberOfEvents = 0) 之前没看清楚，见谅。

**Comment by muchild** [comment]
smart_monkey -a BundleID -n 1 -d //Users/jane/Documents -t 70 --event-number 0 ，monkey.config.numberOfEvents仍然显示为：99999999，能否告知下原因。。

**Comment by vigossjjj** [comment]
按时间执行的话会将事件数设置为99999999，理论上认为99999999个事件执行的耗时可以满足测试耗时，目前这种方案不是很安全，后续可以改进，如果有好的方案可以提交pull request
