### ISSUE TITLE
WARN: no response in log, trigger re-launch action.跳转到别app后，monkey自己断掉了

### ISSUE THREAD

**Issue by muchild** [vigossjjj/CrashMonkey4IOS#25]
WARN: no response in log, trigger re-launch action.
语句：smart_monkey -a BundleID -n 1 -d //Users/jane/Documents -t 900 --event-number 0
这边在执行过程中，跳转到了天气app，出现上述log，接着monkey就自己断掉了。在index中显示为OK，但是没有执行完。
![1](https://cloud.githubusercontent.com/assets/5026824/9879016/241b8820-5bf8-11e5-95df-bf31a50f1332.jpg)

**Comment by JennyLi90** [comment]
我也遇到了这个问题，有什么解决方案吗？命令行里面一致重复WARN: no response in log, trigger re-launch action

**Comment by RogerGan** [comment]
@jane1229 @JennyLi90 应该已经解决了，是兼容性问题

**Comment by muchild** [comment]
@RogerGan 今天有新版本？

**Comment by RogerGan** [comment]
直接最新代码就是了

**Comment by RogerGan** [comment]
@jane1229 我刚才提了一段代码，你再试一下
