### ISSUE TITLE
Unable to open device file './OTAUpdate-2015-03-11-10-10-24.ips' (10). Skipping...

### ISSUE THREAD

**Issue by devilsroar** [vigossjjj/CrashMonkey4IOS#27]
环境：
xcode6.4
IOS 8.4.1

smart_mokey -a xxx -w xxx -n 1000

一直报如题的错，何解？

log输出如下：
INSTRUMENTS_TRACE_PATH : /Users/chenzheng/smart_monkey_result/report_20150917162911/result_000/*.trace
RESULT_BASE_PATH : /Users/chenzheng/smart_monkey_result/report_20150917162911/result_000/smart_monkey_result
{:app_path=>"com.pinganfu.ent.pluginboard", :device=>"50bc4656d9fcd1c1b7d66ec3dac849729799e84b", :run_count=>1000, :time_limit_sec=>nil, :detail_event_count=>50}
=================================== Start Test (1/1000) =======================================
Unable to open device file './OTAUpdate-2015-03-11-10-10-24.ips' (10). Skipping...
Attempting iOS device system log capture via deviceconsole.
BundleID was found: com.xxxx.xxx
Run: ["instruments", "-w", "50bc4656d9fcd1c1b7d66ec3dac849729799e84b", "-t", "/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate", "com.pinganfu.ent.pluginboard", "-e", "UIASCRIPT", "/Users/chenzheng/smart_monkey_result/report_20150917162911/result_000/smart_monkey_result/report_20150917174320/custom.js", "-e", "UIARESULTSPATH", "/Users/chenzheng/smart_monkey_result/report_20150917162911/result_000/smart_monkey_result/report_20150917174320"]
Stop iOS system log capture.
Unable to open device file './OTAUpdate-2015-03-11-10-10-24.ips' (10). Skipping...

**Comment by vigossjjj** [comment]
清除一下iPhone内的crash文件
