### ISSUE TITLE
启动多台真机测试时报错

### ISSUE THREAD

**Issue by rigelxu** [vigossjjj/CrashMonkey4IOS#28]
尝试在终端启动测试，指定两台真机，只有其中一台可以正常运行，另外一台偶尔可以动一下，基本上不会执行操作，并且报如下错误：
WebKit Threading Violation - initial use of WebKit from a secondary thread。

请问是否是不支持多台设备同时执行 Monkey

**Comment by RogerGan** [comment]
@xrj277427509 bingo!  

 UI Automation is a single process Instrument. As such, you cannot use it simultaneously on multiple devices.

你可以装个虚拟机跑2台机器
