### ISSUE TITLE
真机上跑money，提示如下

### ISSUE THREAD

**Issue by michelleli08** [vigossjjj/CrashMonkey4IOS#29]
在真机上跑monkey,提示：
Instruments Trace Error : Target failed to run: Permission to debug xxx.xxx.xxxx.test was denied. The app must be signed with a development identity (e.g. iOS Developer).

**Comment by RogerGan** [comment]
@michelleli08 是app的签名问题，需要使用开发者证书签名的app才可以跑测试

**Comment by yefankongge** [comment]
@RogerGan 发布证书打的包，要如何修改才能跑这个monkey
