### ISSUE TITLE
iphone6p 越狱机 ios8.0.2  运行monkey 手机卡死，monkey能够继续运行，日志无异常

### ISSUE THREAD

**Issue by 1990yanjing** [vigossjjj/CrashMonkey4IOS#32]

**Comment by RogerGan** [comment]
http://stackoverflow.com/questions/26390000/application-hangs-when-profiling-with-instrument-in-xcode-6-0-1

有可能是NSLog太多导致的，建议定位一下

**Comment by vigossjjj** [comment]
没有更新，暂时认为问题已解决
