### ISSUE TITLE
请问下，怎么验证第一次跑的monkey出现的crash已经被修复了？

### ISSUE THREAD

**Issue by muchild** [vigossjjj/CrashMonkey4IOS#33]
请问下，怎么验证之前一次跑的monkey中出现的crash已经被修复了？
请帮忙解答一下

ps：
周一去借手机验证来之前的问题

**Comment by vigossjjj** [comment]
iOS的monkey为随机时间测试，也不会记录事件顺序，目前暂不支持与android类似的seed机制，所以无法按照之前的事件流再次执行验证，即使支持，由于环境的细小差异可以能导致无法做到准确的事件流回放，建议采用持续性长时间测试，或者与RD协商修复的场景，再对特定场景进行复测
