### ISSUE TITLE
index里的Incident Identifier和crashlog里面显示不一致，iphone系统显示也不一致

### ISSUE THREAD

**Issue by muchild** [vigossjjj/CrashMonkey4IOS#35]
![111](https://cloud.githubusercontent.com/assets/5026824/10139151/3acb2b16-6634-11e5-8e5a-dc242e6d3202.jpg)
![222](https://cloud.githubusercontent.com/assets/5026824/10139152/3baceb8c-6634-11e5-90ff-1a901c87a01e.jpg)

**Comment by vigossjjj** [comment]
1.首先要明确crashlog是iOS自动生成的与CrashMonkey无关。
2.Incident Identifier非设备UDID
3.Hardware Model: iPhone6,2 是代表iPhone的研发代号，可以查阅相关资料，每一代iPhone都会有一个代号。iPhone6,2 代表iPhone5s
