### ISSUE TITLE
It doesn't work on iOS8.4 with Xcode7 beta4

### ISSUE THREAD

**Issue by huaping** [vigossjjj/CrashMonkey4IOS#36]
The following is the output, I don't have any experience  on iOS SW development, I don't know how and where to start with. is the crashmonkey compatible with the new iOS/XCode version?
###### #########outputs:

./smart_monkey -w dc762b3adc05cb21cbbc26ddd69e803d77 -a com.youkong
INSTRUMENTS_TRACE_PATH : /Users/huaping/Downloads/CrashMonkey4IOS-master/bin/*.trace
RESULT_BASE_PATH : /Users/huaping/Downloads/CrashMonkey4IOS-master/bin/smart_monkey_result
{:device=>"dc762b3adc05cb21cbbc26ddd69e803d77", :app_path=>"com.youkong", :run_count=>1, :time_limit_sec=>nil, :detail_event_count=>50}
=================================== Start Test (1/1) =======================================
Attempting iOS device system log capture via deviceconsole.
BundleID was found: com.youkong
Run: ["instruments", "-w", "dc762b3adc05cb21cbbc26ddd69e803d77", "-t", "/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate", "com.youkong", "-e", "UIASCRIPT", "/Users/huaping/Downloads/CrashMonkey4IOS-master/bin/smart_monkey_result/report_20151008112104/custom.js", "-e", "UIARESULTSPATH", "/Users/huaping/Downloads/CrashMonkey4IOS-master/bin/smart_monkey_result/report_20151008112104"]
Stop iOS system log capture.
Find new crash report: /Users/huaping/Downloads/CrashMonkey4IOS-master/bin/smart_monkey_result/report_20151008112104/Run 1/stacks-2015-10-08-093117.crash

**Comment by vigossjjj** [comment]
Xcode7正式版应该没有问题
