### ISSUE TITLE
跑monkey过程中，手机灭屏后无法点亮，且终端显示还在继续跑

### ISSUE THREAD

**Issue by muchild** [vigossjjj/CrashMonkey4IOS#37]
跑monkey过程中，手机灭屏后无法点亮，且终端显示还在继续跑
系统log有这句：<Error>: CoreLocation: Discarding message for event 0 because of too many unprocessed messages

**Comment by vigossjjj** [comment]
贴出具体测试环境及日志

**Comment by boxerxing** [comment]
我在自动化测试（UIAutomation框架）执行时再长时间运行后也出现过设备屏幕熄灭后无法手动点亮的现象，使手机恢复的方式通过充电或者电源键加home键长按恢复，目前不确定是什么原因。我觉得这不是mnokey的问题，可能和instrument工具有关
