### ISSUE TITLE
libxml2-2.9.2.tar.gz 无法下载

### ISSUE THREAD

**Issue by zhangkeqinga** [vigossjjj/CrashMonkey4IOS#40]
curl: (56) Recv failure: Connection reset by peer
Error: Failed to download resource "libxml2"
Download failed: ftp://xmlsoft.org/libxml2/libxml2-2.9.2.tar.gz

**Comment by daboluo** [comment]
翻墙啊

**Comment by vigossjjj** [comment]
网络环境问题
