### ISSUE TITLE
在simulator上面测试没有问题，在真机mini2和iPhone6i上都报错

### ISSUE THREAD

**Issue by wangfei1981** [vigossjjj/CrashMonkey4IOS#41]
报错如下：

XXX@JackPro  ~/iOSCheck/IPAs  smart_monkey -a com.tencent.qjnn
INSTRUMENTS_TRACE_PATH : /Users/liuyi/iOSCheck/IPAs/*.trace
RESULT_BASE_PATH : /Users/liuyi/iOSCheck/IPAs/smart_monkey_result
{:app_path=>"com.tencent.qjnn", :run_count=>1, :time_limit_sec=>nil, :detail_event_count=>50}
=================================== Start Test (1/1) =======================================
Attempting iOS device system log capture via deviceconsole.
BundleID was found: com.tencent.qjnn
Run: ["instruments", "-w", "7824fdd4d7be6d8074022e8c14b8581082e32acb", "-t", "/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate", "com.tencent.qjnn", "-e", "UIASCRIPT", "/Users/liuyi/iOSCheck/IPAs/smart_monkey_result/report_20151201100305/custom.js", "-e", "UIARESULTSPATH", "/Users/liuyi/iOSCheck/IPAs/smart_monkey_result/report_20151201100305"]
Stop iOS system log capture.

是真机必须要有开发者证书才行吗？

**Comment by vigossjjj** [comment]
是的，真机测试需要开发证书，1.device在证书内 2.app为对应的developer证书签发
