### ISSUE TITLE
ERROR:  Could not find a valid gem 'smart_monkey' (>= 0) in any repository

### ISSUE THREAD

**Issue by perfmeta** [vigossjjj/CrashMonkey4IOS#42]
ERROR:  Could not find a valid gem 'smart_monkey' (>= 0) in any repository

**Comment by vigossjjj** [comment]
应该是你的本地环境问题，镜像配置之类的

**Comment by sunshinekxy** [comment]
我遇到了类似的问题，我的报错为：
Mac-mini:~ wade$ gem install smart_monkey
ERROR:  Could not find a valid gem 'smart_monkey' (>= 0), here is why:
          Unable to download data from https://ruby.taobao.org/ - server did not return a valid file (https://ruby.taobao.org/latest_specs.4.8.gz)
我的解决办法是：我用sudo gem install smart_monkey  然后输入你的密码就好啦~
