### ISSUE TITLE
到了安装gem install smart_monkey就一直说找不到文件了？？

### ISSUE THREAD

**Issue by wxpokay** [vigossjjj/CrashMonkey4IOS#44]
ritawudeMac-mini:~ ritawu$ gem install smart_monkey
ERROR: Could not find a valid gem 'smart_monkey' (>= 0), here is why:
Unable to download data from http://ruby.taobao.org/ - bad response Not Found 404 (http://ruby.taobao.org/specs.4.8.gz)
这个一直错误要怎么解决？淘宝镜像已经安装好了

**Comment by zhen-lit** [comment]
警告提示： WARNING:  Unable to pull data from 'http://ruby.taobao.org/': bad response Not Found 404 (http://ruby.taobao.org/latest_specs.4.8.gz)
解决方案： gem sources --remove http://ruby.taobao.org/
检查： gem sources -l
**\* CURRENT SOURCES ***

https://ruby.taobao.org/
只有一个ruby的sources才正确。

完成之后继续安装下面步骤：
- brew install -HEAD ideviceinstaller
- brew install libimobiledevice
- brew install imagemagick
- sudo gem install smart_monkey,
