### ISSUE TITLE
系统版本都是一样9.2，apple 6，6p 错误提示如下，apple5，5s都能正常跑起来

### ISSUE THREAD

**Issue by zhen-lit** [vigossjjj/CrashMonkey4IOS#47]
/Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.5.0/lib/smart_monkey/monkey_runner.rb:218:in ``': Interrupt
    from /Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.5.0/lib/smart_monkey/monkey_runner.rb:218:in`devices'
    from /Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.5.0/lib/smart_monkey/monkey_runner.rb:201:in `device'
    from /Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.5.0/lib/smart_monkey/monkey_runner.rb:236:in`is_simulator'
    from /Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.5.0/lib/smart_monkey/monkey_runner.rb:173:in `list_app'
    from /Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.5.0/lib/smart_monkey/monkey_runner.rb:23:in`run'
    from /Library/Ruby/Gems/2.0.0/gems/smart_monkey-0.5.0/bin/smart_monkey:58:in `<top (required)>'
    from /usr/local/bin/smart_monkey:23:in`load'
    from /usr/local/bin/smart_monkey:23:in `<main>'

**Comment by boxerxing** [comment]
最新的版本不复现
