### ISSUE TITLE
总是提示WebKit Threading Violation - initial use of WebKit from a secondary thread.

### ISSUE THREAD

**Issue by Nukker** [vigossjjj/CrashMonkey4IOS#56]
1. mac环境连接运行smart_monkey -a com.yingzt.invest-enterprise-distribution -n 3 -t 500
2. log如下  {:app_path=>"com.yingzt.invest-enterprise-distribution", :run_count=>3, :time_limit_sec=>500, :detail_event_count=>50}
   2016-03-30 14:35:58.581 instruments[17787:7286541] WebKit Threading Violation - initial use of WebKit from a secondary thread.
   3.备注：已经确定后台已经没有此app在运行中

**Comment by boxerxing** [comment]
@Nukker 
1. 去请先确认真机下 设置-开发者-UI AUTOMATION 是否被禁用，8.3以下的iOS系统该选项默认是关闭的，测试时必须打开。
2. 查看本地的webkit是否安装成功，安装命令如下：
`brew install ios-webkit-debug-proxy`
以上希望你够帮助到你
