### ISSUE TITLE
 Could not find a valid gem 'erubis' (>= 0) in any repository

### ISSUE THREAD

**Issue by yanzhangzhangyan** [vigossjjj/CrashMonkey4IOS#61]
安装过程使用reset.sh时,报 Could not find a valid gem 'erubis' (>= 0) in any repository，使用sudo gem install erubis单独安装也会报此错误

**Comment by boxerxing** [comment]
@yanzhangzhangyan 请直接参看作者的README进行一步一步的安装，尽量不使用reset.sh，脚本暂时不维护了，Troubleshooting中是当时第一版时直接安装的问题，里面建议把项目用到的组件一个个手动安装好，这样在安装过程中易于定位环境问题
