### ISSUE TITLE
iOS 9.3 模拟器运行不起来

### ISSUE THREAD

**Issue by lizhaobomb** [vigossjjj/CrashMonkey4IOS#63]
➜  ~ smart_monkey -a EnNewSim -w C4141E61-F271-4B99-8852-100444ED87F4 -d ~/Desktop/Result/
INSTRUMENTS_TRACE_PATH : /Users/_/_.trace
RESULT_BASE_PATH : /Users/*/Desktop/Result
{:app_path=>"com.ennew.customer", :device=>"C4141E61-F271-4B99-8852-100444ED87F4", :result_base_dir=>"/Users/lizhao/Desktop/Result", :run_count=>1, :time_limit_sec=>nil, :detail_event_count=>50}
2016-06-21 11:36:20.694 instruments[59056:2199355] WebKit Threading Violation - initial use of WebKit from a secondary thread.
=================================== Start Test (1/1) =======================================
2016-06-21 11:36:23.664 instruments[59082:2199568] WebKit Threading Violation - initial use of WebKit from a secondary thread.
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0:`idevicecrashreport -u C4141E61-F271-4B99-8852-100444ED87F4 (Simulator) -e -k /Users/lizhao/Desktop/Result/report_20160621113618/crash_1'
Attempting iOS device system log capture via deviceconsole.
Stop iOS system log capture.
Invalid device, Please given a vaild device!

**Comment by lizhaobomb** [comment]
1、is_simulator 方法 xcode7里instruments不带Simulator改用“-”判断，  …
2、还有就是simulator的格式有变化之前是
iPhone 6 (8.3 Simulator) [E23DE92A-B6B1-4AEF-9632-4DA8DD7CE630]
现在是
iPhone 6 (9.3) [63BDF4FF-DA96-4B1F-9A56-2D67A9E77C24] （Simulator)
所以把find_device 方法里的device_line.strip.split("[")[1].delete “]”改成
device_line.strip.split("[")[1].split("]")[0]

**Comment by CNMBJR** [comment]
小白请问：find_device 方法在哪里。。？

**Comment by boxerxing** [comment]
@CNMBJR  源码中
