### ISSUE TITLE
IOS10跑不起来

### ISSUE THREAD

**Issue by SukiLei** [vigossjjj/CrashMonkey4IOS#72]
用IOS10跑monkey， 提示：
Instruments Trace Error : Target failed to run: Permission to debug com.xxx.xxxx was denied. The app must be signed with a development identity (e.g. iOS Developer).
已确认app是有签名的，并且之前同样的app在ios9.3.4，9.3.5都是可以跑的。
麻烦啦~

**Comment by qyqzhlw** [comment]
你9.3.5 也跑到起来嘛，xcode  是什么版本      我的9.3.5 死活跑不起来

**Comment by SukiLei** [comment]
@qyqzhlw   我的9.3.5可以跑的，xcode是7.3版本的。

**Comment by lemonadam** [comment]
iOS 10 里 没有automation 了，肯定跑步起来。

**Comment by SukiLei** [comment]
@lemonadam 嗯，是的呢。这个有办法解决不？

**Comment by vigossjjj** [comment]
苹果再xcode8以后移除了UIAutomation，所以基于这种方式的Monkey是不支持的。目前正在开发新版基于XCTest-WebDriverAgent版，但执行效率并不理想，不确定放出时间
