### ISSUE TITLE
报错“Could not connect to lockdownd”

### ISSUE THREAD

**Issue by Tomorrow1993** [vigossjjj/CrashMonkey4IOS#76]
运行报错“Could not connect to lockdownd”

**Comment by R-U-N** [comment]
同样的问题

**Comment by vigossjjj** [comment]
这个是libimobieldevice iOS 10的兼容性问题，下载最新的代码本地编译

**Comment by Tomorrow1993** [comment]
你好 我是直接下载的zip包 解压了不知道怎么编译 求指点 麻烦了🙏

**Comment by Tomorrow1993** [comment]
我升级到xcode8了

**Comment by Tomorrow1993** [comment]
本地具体编译哪个文件呢？还有我升级到Xcode8了 原来的实现方案不能用了吧？小白实在不懂 麻烦了 🙏
