### ISSUE TITLE
Downloading https://www.openssl.org/source/openssl-1.0.2.tar.gz 404

### ISSUE THREAD

**Issue by LuciferFang** [vigossjjj/CrashMonkey4IOS#9]
执行 brew install libimobiledevice  在Terminal, ==> Installing libimobiledevice dependency: openssl
Warning: Building source; cellar of openssl's bottle is /usr/local/Cellar
==> Downloading https://www.openssl.org/source/openssl-1.0.2.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://raw.githubusercontent.com/DomT4/LibreMirror/master/OpenS

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "openssl"
Download failed: https://raw.githubusercontent.com/DomT4/LibreMirror/master/OpenSSL/openssl-1.0.2.tar.gz

**Comment by vigossjjj** [comment]
应该和你的网络因素相关，可以自行google解决怎样安装libimobiledevice
